name: Close Stale Issues

on:
  schedule:
    - cron: '0 12 * * *' # 每天晚上8:00 (台灣時間)

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/stale@v9.1.0
        with:
          stale-issue-message: '這個 Issue 過期了，將在 7 天後關閉！'
          days-before-stale: 30
          days-before-close: 7
          stale-label: 'stale'
          exempt-labels: 'pinned,security'
          delete-branch: true
